# Tasan et.al. 2015 Acta Materalia
# Tasan et.al. 2015 International Journal of Plasticity
# Diehl et.al. 2015 Meccanica
Martensite:
  lattice: cI
  mechanical:
    elastic: {C_11: 417.4e+9, C_12: 242.4e+9, C_44: 211.1e+9, type: Hooke}
    plastic:
      N_sl: [12, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl-sl: 563.0e+9
      h_sl-sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      type: phenopowerlaw
      xi_0_sl: [405.8e+6, 456.7e+6]
      xi_inf_sl: [872.9e+6, 971.2e+6]
